language: python
python:
    - "3.6"

services:
    - docker
    - postgresql

before_script:
    - pip install docker-compose
    - psql -c 'create database recipesdb;' -U postgres

script:
    - docker-compose run app sh -c "python manage.py makemigrations"
    - docker-compose run app sh -c "python manage.py migrate"
    - docker-compose run app sh -c "python manage.py test && flake8"
